---
version: '3'

services:
  server:
    build:
      context: v1
      dockerfile: Dockerfile
    image: rayshoo/argocd-api-server:v1.0.0-alpha-0
    ports:
    - 3000:3000
    env_file:
    - v1/.env
