---
apiVersion: v1
data:
  ARGOCD_PROTOCOL: aHR0cA==
  ARGOCD_HOST: YXJnb2NkLXNlcnZlci5hcmdvY2Quc3Zj
  ARGOCD_PORT: ODA=
  ARGOCD_USERNAME: YWRtaW4=
  ARGOCD_PASSWORD: 
kind: Secret
metadata:
  name: argocd-api-server
type: Opaque
