---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-api-server
  name: argocd-api-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: argocd-api-server